from fedora:27
RUN yum update -y
RUN dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
RUN dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
RUN dnf -y install ffmpeg
run yum install -y opus python3-pip python3-devel libffi-devel gcc make ca-certificates
run pip3 install discord.py
run pip3 install -U discord.py[voice]
run pip3 install PyNaCl
run pip3 install youtube_dl
cmd ["python3", "main.py"]
